/**
 *
 *  Option.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Option.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Option::Cols::_id = "id";
const std::string Option::Cols::_text = "text";
const std::string Option::primaryKeyName = "id";
const bool Option::hasPrimaryKey = true;
const std::string Option::tableName = "option";

const std::vector<typename Option::MetaData> Option::metaData_ = {
    {"id", "uint64_t", "integer", 8, 1, 1, 1},
    {"text", "std::string", "text", 0, 0, 0, 0}};
const std::string &Option::getColumnName(size_t index) noexcept(false) {
  assert(index < metaData_.size());
  return metaData_[index].colName_;
}
Option::Option(const Row &r, const ssize_t indexOffset) noexcept {
  if (indexOffset < 0) {
    if (!r["id"].isNull()) {
      id_ = std::make_shared<uint64_t>(r["id"].as<uint64_t>());
    }
    if (!r["text"].isNull()) {
      text_ = std::make_shared<std::string>(r["text"].as<std::string>());
    }
  } else {
    size_t offset = (size_t)indexOffset;
    if (offset + 2 > r.size()) {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if (!r[index].isNull()) {
      id_ = std::make_shared<uint64_t>(r[index].as<uint64_t>());
    }
    index = offset + 1;
    if (!r[index].isNull()) {
      text_ = std::make_shared<std::string>(r[index].as<std::string>());
    }
  }
}

Option::Option(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 2) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    dirtyFlag_[0] = true;
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<uint64_t>(
          (uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      text_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
}

Option::Option(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    dirtyFlag_[0] = true;
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
    }
  }
  if (pJson.isMember("text")) {
    dirtyFlag_[1] = true;
    if (!pJson["text"].isNull()) {
      text_ = std::make_shared<std::string>(pJson["text"].asString());
    }
  }
}

void Option::updateByMasqueradedJson(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
  if (pMasqueradingVector.size() != 2) {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if (!pMasqueradingVector[0].empty() &&
      pJson.isMember(pMasqueradingVector[0])) {
    if (!pJson[pMasqueradingVector[0]].isNull()) {
      id_ = std::make_shared<uint64_t>(
          (uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
    }
  }
  if (!pMasqueradingVector[1].empty() &&
      pJson.isMember(pMasqueradingVector[1])) {
    dirtyFlag_[1] = true;
    if (!pJson[pMasqueradingVector[1]].isNull()) {
      text_ = std::make_shared<std::string>(
          pJson[pMasqueradingVector[1]].asString());
    }
  }
}

void Option::updateByJson(const Json::Value &pJson) noexcept(false) {
  if (pJson.isMember("id")) {
    if (!pJson["id"].isNull()) {
      id_ = std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
    }
  }
  if (pJson.isMember("text")) {
    dirtyFlag_[1] = true;
    if (!pJson["text"].isNull()) {
      text_ = std::make_shared<std::string>(pJson["text"].asString());
    }
  }
}

const uint64_t &Option::getValueOfId() const noexcept {
  const static uint64_t defaultValue = uint64_t();
  if (id_)
    return *id_;
  return defaultValue;
}
const std::shared_ptr<uint64_t> &Option::getId() const noexcept { return id_; }
void Option::setId(const uint64_t &pId) noexcept {
  id_ = std::make_shared<uint64_t>(pId);
  dirtyFlag_[0] = true;
}
const typename Option::PrimaryKeyType &Option::getPrimaryKey() const {
  assert(id_);
  return *id_;
}

const std::string &Option::getValueOfText() const noexcept {
  const static std::string defaultValue = std::string();
  if (text_)
    return *text_;
  return defaultValue;
}
const std::shared_ptr<std::string> &Option::getText() const noexcept {
  return text_;
}
void Option::setText(const std::string &pText) noexcept {
  text_ = std::make_shared<std::string>(pText);
  dirtyFlag_[1] = true;
}
void Option::setText(std::string &&pText) noexcept {
  text_ = std::make_shared<std::string>(std::move(pText));
  dirtyFlag_[1] = true;
}
void Option::setTextToNull() noexcept {
  text_.reset();
  dirtyFlag_[1] = true;
}

void Option::updateId(const uint64_t id) {
  id_ = std::make_shared<uint64_t>(id);
}

const std::vector<std::string> &Option::insertColumns() noexcept {
  static const std::vector<std::string> inCols = {"text"};
  return inCols;
}

void Option::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getText()) {
      binder << getValueOfText();
    } else {
      binder << nullptr;
    }
  }
}

const std::vector<std::string> Option::updateColumns() const {
  std::vector<std::string> ret;
  if (dirtyFlag_[1]) {
    ret.push_back(getColumnName(1));
  }
  return ret;
}

void Option::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
  if (dirtyFlag_[1]) {
    if (getText()) {
      binder << getValueOfText();
    } else {
      binder << nullptr;
    }
  }
}
Json::Value Option::toJson() const {
  Json::Value ret;
  if (getId()) {
    ret["id"] = (Json::UInt64)getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getText()) {
    ret["text"] = getValueOfText();
  } else {
    ret["text"] = Json::Value();
  }
  return ret;
}

Json::Value Option::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const {
  Json::Value ret;
  if (pMasqueradingVector.size() == 2) {
    if (!pMasqueradingVector[0].empty()) {
      if (getId()) {
        ret[pMasqueradingVector[0]] = (Json::UInt64)getValueOfId();
      } else {
        ret[pMasqueradingVector[0]] = Json::Value();
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (getText()) {
        ret[pMasqueradingVector[1]] = getValueOfText();
      } else {
        ret[pMasqueradingVector[1]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if (getId()) {
    ret["id"] = (Json::UInt64)getValueOfId();
  } else {
    ret["id"] = Json::Value();
  }
  if (getText()) {
    ret["text"] = getValueOfText();
  } else {
    ret["text"] = Json::Value();
  }
  return ret;
}

bool Option::validateJsonForCreation(const Json::Value &pJson,
                                     std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, true))
      return false;
  }
  if (pJson.isMember("text")) {
    if (!validJsonOfField(1, "text", pJson["text"], err, true))
      return false;
  }
  return true;
}
bool Option::validateMasqueradedJsonForCreation(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
  if (pMasqueradingVector.size() != 2) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty()) {
      if (pJson.isMember(pMasqueradingVector[0])) {
        if (!validJsonOfField(0, pMasqueradingVector[0],
                              pJson[pMasqueradingVector[0]], err, true))
          return false;
      }
    }
    if (!pMasqueradingVector[1].empty()) {
      if (pJson.isMember(pMasqueradingVector[1])) {
        if (!validJsonOfField(1, pMasqueradingVector[1],
                              pJson[pMasqueradingVector[1]], err, true))
          return false;
      }
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Option::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
  if (pJson.isMember("id")) {
    if (!validJsonOfField(0, "id", pJson["id"], err, false))
      return false;
  } else {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if (pJson.isMember("text")) {
    if (!validJsonOfField(1, "text", pJson["text"], err, false))
      return false;
  }
  return true;
}
bool Option::validateMasqueradedJsonForUpdate(
    const Json::Value &pJson,
    const std::vector<std::string> &pMasqueradingVector, std::string &err) {
  if (pMasqueradingVector.size() != 2) {
    err = "Bad masquerading vector";
    return false;
  }
  try {
    if (!pMasqueradingVector[0].empty() &&
        pJson.isMember(pMasqueradingVector[0])) {
      if (!validJsonOfField(0, pMasqueradingVector[0],
                            pJson[pMasqueradingVector[0]], err, false))
        return false;
    } else {
      err =
          "The value of primary key must be set in the json object for update";
      return false;
    }
    if (!pMasqueradingVector[1].empty() &&
        pJson.isMember(pMasqueradingVector[1])) {
      if (!validJsonOfField(1, pMasqueradingVector[1],
                            pJson[pMasqueradingVector[1]], err, false))
        return false;
    }
  } catch (const Json::LogicError &e) {
    err = e.what();
    return false;
  }
  return true;
}
bool Option::validJsonOfField(size_t index, const std::string &fieldName,
                              const Json::Value &pJson, std::string &err,
                              bool isForCreation) {
  switch (index) {
  case 0:
    if (pJson.isNull()) {
      err = "The " + fieldName + " column cannot be null";
      return false;
    }
    if (isForCreation) {
      err = "The automatic primary key cannot be set";
      return false;
    }
    if (!pJson.isUInt64()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  case 1:
    if (pJson.isNull()) {
      return true;
    }
    if (!pJson.isString()) {
      err = "Type error in the " + fieldName + " field";
      return false;
    }
    break;
  default:
    err = "Internal error in the server";
    return false;
    break;
  }
  return true;
}
